name: social_media_app_starter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  carousel_slider: ^4.0.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1
  http: ^0.13.4
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  cloud_firestore: ^3.1.0
  image_picker: ^0.8.4+4
  firebase_storage: ^10.2.0
  font_awesome_flutter: ^9.2.0
  flutter_neumorphic: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
